base_url = "https://subash-aryal.com.np"
title = "Subash Aryal"

compile_sass = true

highlight_code = true

build_search_index = false

check_external_links = true

taxonomies = [
    { name = "tags", rss = true },
    { name = "authors", rss = true }
]

[extra]
show_word_count = true
show_reading_time = true

date_format = "%a %b %e, %Y"

home = "home"

sam_menu = [
    { text = "posts", link = "/posts" },
    { text = "about", link = "/about" },
    { text = "projects", link = "/projects" },
    { text = "github", link = "https://github.com/subashz" }
]

sam_bottom_menu = false

[extra.sam_footer]
text = ""
